/**
 * Flexily Constants
 *
 * Yoga-compatible constants for flexbox layout.
 * These match Yoga's enum values exactly for drop-in compatibility.
 */
export declare const FLEX_DIRECTION_COLUMN = 0;
export declare const FLEX_DIRECTION_COLUMN_REVERSE = 1;
export declare const FLEX_DIRECTION_ROW = 2;
export declare const FLEX_DIRECTION_ROW_REVERSE = 3;
export declare const WRAP_NO_WRAP = 0;
export declare const WRAP_WRAP = 1;
export declare const WRAP_WRAP_REVERSE = 2;
export declare const ALIGN_AUTO = 0;
export declare const ALIGN_FLEX_START = 1;
export declare const ALIGN_CENTER = 2;
export declare const ALIGN_FLEX_END = 3;
export declare const ALIGN_STRETCH = 4;
export declare const ALIGN_BASELINE = 5;
export declare const ALIGN_SPACE_BETWEEN = 6;
export declare const ALIGN_SPACE_AROUND = 7;
export declare const ALIGN_SPACE_EVENLY = 8;
export declare const JUSTIFY_FLEX_START = 0;
export declare const JUSTIFY_CENTER = 1;
export declare const JUSTIFY_FLEX_END = 2;
export declare const JUSTIFY_SPACE_BETWEEN = 3;
export declare const JUSTIFY_SPACE_AROUND = 4;
export declare const JUSTIFY_SPACE_EVENLY = 5;
export declare const EDGE_LEFT = 0;
export declare const EDGE_TOP = 1;
export declare const EDGE_RIGHT = 2;
export declare const EDGE_BOTTOM = 3;
export declare const EDGE_START = 4;
export declare const EDGE_END = 5;
export declare const EDGE_HORIZONTAL = 6;
export declare const EDGE_VERTICAL = 7;
export declare const EDGE_ALL = 8;
export declare const GUTTER_COLUMN = 0;
export declare const GUTTER_ROW = 1;
export declare const GUTTER_ALL = 2;
export declare const DISPLAY_FLEX = 0;
export declare const DISPLAY_NONE = 1;
export declare const POSITION_TYPE_STATIC = 0;
export declare const POSITION_TYPE_RELATIVE = 1;
export declare const POSITION_TYPE_ABSOLUTE = 2;
export declare const OVERFLOW_VISIBLE = 0;
export declare const OVERFLOW_HIDDEN = 1;
export declare const OVERFLOW_SCROLL = 2;
export declare const DIRECTION_INHERIT = 0;
export declare const DIRECTION_LTR = 1;
export declare const DIRECTION_RTL = 2;
export declare const MEASURE_MODE_UNDEFINED = 0;
export declare const MEASURE_MODE_EXACTLY = 1;
export declare const MEASURE_MODE_AT_MOST = 2;
export declare const UNIT_UNDEFINED = 0;
export declare const UNIT_POINT = 1;
export declare const UNIT_PERCENT = 2;
export declare const UNIT_AUTO = 3;
export declare const UNIT_FIT_CONTENT = 4;
export declare const UNIT_SNUG_CONTENT = 5;
