/**
 * Font atlas generator — rasterizes a TTF font to a grayscale bitmap atlas.
 *
 * Uses opentype.js to parse the font and @napi-rs/canvas to rasterize
 * glyphs with real antialiasing. Outputs a Zig source file with the
 * atlas data embedded as a byte array.
 *
 * Usage: bun run scripts/gen-font-atlas.ts [font-path] [size]
 *
 * Defaults:
 *   font: /System/Library/Fonts/SFNSMono.ttf (SF Mono)
 *   size: 32 (pixels, renders at this height then can be downsampled)
 */

import { createCanvas } from "@napi-rs/canvas"
import opentype from "opentype.js"
import { writeFileSync } from "fs"
import { resolve } from "path"

const FONT_PATH = process.argv[2] || "/System/Library/Fonts/SFNSMono.ttf"
const RENDER_SIZE = parseInt(process.argv[3] || "32")
const FIRST_CP = 32  // space
const LAST_CP = 126  // ~
const GLYPH_COUNT = LAST_CP - FIRST_CP + 1

console.log(`Font: ${FONT_PATH}`)
console.log(`Render size: ${RENDER_SIZE}px`)
console.log(`Glyphs: ${GLYPH_COUNT} (ASCII ${FIRST_CP}-${LAST_CP})`)

// Load font
const font = opentype.loadSync(FONT_PATH)
console.log(`Font family: ${font.names.fontFamily?.en || "unknown"}`)

// Determine glyph cell dimensions.
// For monospace fonts, all glyphs have the same advance width.
const scale = RENDER_SIZE / font.unitsPerEm
const ascender = Math.ceil(font.ascender * scale)
const descender = Math.ceil(Math.abs(font.descender * scale))
const cellHeight = ascender + descender

// Get advance width from a reference glyph ('M')
const refGlyph = font.charToGlyph("M")
const cellWidth = Math.ceil(refGlyph.advanceWidth * scale)

console.log(`Cell: ${cellWidth}x${cellHeight}px (ascender=${ascender}, descender=${descender})`)

// Render each glyph to a canvas and extract grayscale alpha
const atlas: number[][] = []

for (let cp = FIRST_CP; cp <= LAST_CP; cp++) {
  const canvas = createCanvas(cellWidth, cellHeight)
  const ctx = canvas.getContext("2d")

  // Clear to transparent black
  ctx.clearRect(0, 0, cellWidth, cellHeight)

  // Draw glyph in white — we only care about the alpha channel
  ctx.fillStyle = "#ffffff"
  const glyph = font.charToGlyph(String.fromCharCode(cp))
  const path = glyph.getPath(0, ascender, RENDER_SIZE)
  
  // Convert opentype path to canvas path
  ctx.beginPath()
  for (const cmd of path.commands) {
    switch (cmd.type) {
      case "M": ctx.moveTo(cmd.x, cmd.y); break
      case "L": ctx.lineTo(cmd.x, cmd.y); break
      case "Q": ctx.quadraticCurveTo(cmd.x1, cmd.y1, cmd.x, cmd.y); break
      case "C": ctx.bezierCurveTo(cmd.x1, cmd.y1, cmd.x2!, cmd.y2!, cmd.x, cmd.y); break
      case "Z": ctx.closePath(); break
    }
  }
  ctx.fill()

  // Extract alpha channel as grayscale (0-255)
  const imageData = ctx.getImageData(0, 0, cellWidth, cellHeight)
  const pixels = imageData.data
  const alphas: number[] = []
  for (let i = 0; i < pixels.length; i += 4) {
    alphas.push(pixels[i + 3]) // alpha channel = coverage
  }
  atlas.push(alphas)
}

// Generate Zig source
const lines: string[] = []
lines.push("/// Font atlas — pre-rendered grayscale glyphs from TTF font.")
lines.push(`/// Font: ${font.names.fontFamily?.en || "unknown"}`)
lines.push(`/// Render size: ${RENDER_SIZE}px`)
lines.push("/// Each glyph: grayscale alpha values (0=transparent, 255=opaque).")
lines.push("/// Generated by scripts/gen-font-atlas.ts — DO NOT EDIT.")
lines.push("")
lines.push(`pub const cell_width: u32 = ${cellWidth};`)
lines.push(`pub const cell_height: u32 = ${cellHeight};`)
lines.push(`pub const first_cp: u32 = ${FIRST_CP};`)
lines.push(`pub const last_cp: u32 = ${LAST_CP};`)
lines.push(`pub const glyph_count: u32 = ${GLYPH_COUNT};`)
lines.push(`pub const ascender: u32 = ${ascender};`)
lines.push("")

// Emit as a flat array: glyph_count * cell_width * cell_height bytes
const totalBytes = GLYPH_COUNT * cellWidth * cellHeight
lines.push(`/// Flat atlas: ${GLYPH_COUNT} glyphs × ${cellWidth}×${cellHeight}px = ${totalBytes} bytes.`)
lines.push(`/// Index: (codepoint - ${FIRST_CP}) * ${cellWidth * cellHeight} + row * ${cellWidth} + col`)
lines.push(`pub const data = [_]u8{`)

for (let cp = FIRST_CP; cp <= LAST_CP; cp++) {
  const idx = cp - FIRST_CP
  const alphas = atlas[idx]
  const ch = cp === 92 ? "\\\\" : cp === 39 ? "\\'" : String.fromCharCode(cp)
  lines.push(`    // ${cp} '${ch}'`)
  
  for (let row = 0; row < cellHeight; row++) {
    const rowData: string[] = []
    for (let col = 0; col < cellWidth; col++) {
      const val = alphas[row * cellWidth + col]
      rowData.push(val.toString().padStart(3))
    }
    lines.push(`    ${rowData.join(",")},`)
  }
}

lines.push("};")

const outPath = resolve(import.meta.dir, "../zig/src/font_atlas.zig")
writeFileSync(outPath, lines.join("\n") + "\n")
console.log(`\nWrote ${outPath}`)
console.log(`Atlas size: ${totalBytes} bytes (${(totalBytes / 1024).toFixed(1)} KB)`)
