/**
 * Font atlas generator — rasterizes a TTF font to a grayscale bitmap atlas.
 *
 * Uses opentype.js to parse the font and @napi-rs/canvas to rasterize
 * glyphs with real antialiasing. Outputs a Zig source file with the
 * atlas data embedded as a byte array.
 *
 * Supports multiple Unicode ranges (ASCII, Latin-1, Arrows, Box Drawing, etc.)
 * with O(1) range-based lookup in the generated Zig code.
 *
 * Usage: bun run scripts/gen-font-atlas.ts [font-path] [size]
 *
 * Defaults:
 *   font: /System/Library/Fonts/SFNSMono.ttf (SF Mono)
 *   size: 32 (pixels, renders at this height then can be downsampled)
 */

import { createCanvas } from "@napi-rs/canvas"
import opentype from "opentype.js"
import { writeFileSync } from "fs"
import { resolve } from "path"

const FONT_PATH = process.argv[2] || "/System/Library/Fonts/SFNSMono.ttf"
const RENDER_SIZE = parseInt(process.argv[3] || "32")

// ── Unicode ranges to include ──
// Each range is a dense block. Lookup is O(1) per range, O(n) across ranges
// where n = number of ranges (7). In practice this is 7 comparisons max.
const RANGES: { name: string; first: number; last: number }[] = [
  { name: "ASCII",              first: 0x0020, last: 0x007E }, // 95 glyphs
  { name: "Latin-1 Supplement", first: 0x00A0, last: 0x00FF }, // 96 glyphs (¡¢£¤¥¦§¨©ª«¬®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ)
  { name: "Arrows",             first: 0x2190, last: 0x21FF }, // 112 glyphs (←↑→↓↔↕↖↗↘↙...)
  { name: "Box Drawing",        first: 0x2500, last: 0x257F }, // 128 glyphs (─│┌┐└┘├┤┬┴┼...)
  { name: "Block Elements",     first: 0x2580, last: 0x259F }, // 32 glyphs (▀▁▂▃▄▅▆▇█▉▊▋▌▍▎▏▐░▒▓)
  { name: "Geometric Shapes",   first: 0x25A0, last: 0x25FF }, // 96 glyphs (■□▢▣▤▥▦▧▨▩▪▫▬▭▮▯▰▱▲△...)
  { name: "Misc Symbols",       first: 0x2713, last: 0x2717 }, // 5 glyphs (✓✔✕✖✗)
]

const totalGlyphs = RANGES.reduce((sum, r) => sum + (r.last - r.first + 1), 0)

console.log(`Font: ${FONT_PATH}`)
console.log(`Render size: ${RENDER_SIZE}px`)
console.log(`Ranges: ${RANGES.length}`)
for (const r of RANGES) {
  console.log(`  ${r.name}: U+${r.first.toString(16).toUpperCase().padStart(4, "0")}-U+${r.last.toString(16).toUpperCase().padStart(4, "0")} (${r.last - r.first + 1} glyphs)`)
}
console.log(`Total glyphs: ${totalGlyphs}`)

// Load font
const font = opentype.loadSync(FONT_PATH)
console.log(`Font family: ${font.names.fontFamily?.en || "unknown"}`)

// Determine glyph cell dimensions.
// For monospace fonts, all glyphs have the same advance width.
const scale = RENDER_SIZE / font.unitsPerEm
const ascender = Math.ceil(font.ascender * scale)
const descender = Math.ceil(Math.abs(font.descender * scale))
const cellHeight = ascender + descender

// Get advance width from a reference glyph ('M')
const refGlyph = font.charToGlyph("M")
const cellWidth = Math.ceil(refGlyph.advanceWidth * scale)

console.log(`Cell: ${cellWidth}x${cellHeight}px (ascender=${ascender}, descender=${descender})`)

// ── Render glyphs ──

function renderGlyph(cp: number): number[] {
  const canvas = createCanvas(cellWidth, cellHeight)
  const ctx = canvas.getContext("2d")

  ctx.clearRect(0, 0, cellWidth, cellHeight)
  ctx.fillStyle = "#ffffff"

  const glyph = font.charToGlyph(String.fromCodePoint(cp))
  const path = glyph.getPath(0, ascender, RENDER_SIZE)

  ctx.beginPath()
  for (const cmd of path.commands) {
    switch (cmd.type) {
      case "M": ctx.moveTo(cmd.x, cmd.y); break
      case "L": ctx.lineTo(cmd.x, cmd.y); break
      case "Q": ctx.quadraticCurveTo(cmd.x1, cmd.y1, cmd.x, cmd.y); break
      case "C": ctx.bezierCurveTo(cmd.x1, cmd.y1, cmd.x2!, cmd.y2!, cmd.x, cmd.y); break
      case "Z": ctx.closePath(); break
    }
  }
  ctx.fill()

  const imageData = ctx.getImageData(0, 0, cellWidth, cellHeight)
  const pixels = imageData.data
  const alphas: number[] = []
  for (let i = 0; i < pixels.length; i += 4) {
    alphas.push(pixels[i + 3])
  }
  return alphas
}

// Render all glyphs across all ranges
const allGlyphs: { cp: number; alphas: number[] }[] = []
for (const range of RANGES) {
  for (let cp = range.first; cp <= range.last; cp++) {
    allGlyphs.push({ cp, alphas: renderGlyph(cp) })
  }
}

console.log(`Rendered ${allGlyphs.length} glyphs`)

// ── Generate Zig source ──

const lines: string[] = []
lines.push("/// Font atlas — pre-rendered grayscale glyphs from TTF font.")
lines.push(`/// Font: ${font.names.fontFamily?.en || "unknown"}`)
lines.push(`/// Render size: ${RENDER_SIZE}px`)
lines.push("/// Each glyph: grayscale alpha values (0=transparent, 255=opaque).")
lines.push("/// Supports multiple Unicode ranges with O(1) lookup per range.")
lines.push("/// Generated by scripts/gen-font-atlas.ts — DO NOT EDIT.")
lines.push("")
lines.push(`pub const cell_width: u32 = ${cellWidth};`)
lines.push(`pub const cell_height: u32 = ${cellHeight};`)
lines.push(`pub const glyph_count: u32 = ${totalGlyphs};`)
lines.push(`pub const ascender: u32 = ${ascender};`)
lines.push(`pub const cell_size: u32 = cell_width * cell_height;`)
lines.push("")

// Emit range metadata
lines.push(`/// Unicode ranges — each is a dense block in the atlas.`)
lines.push(`pub const Range = struct { first: u32, last: u32, offset: u32 };`)
lines.push(`pub const ranges = [_]Range{`)
let offset = 0
for (const r of RANGES) {
  const count = r.last - r.first + 1
  lines.push(`    .{ .first = 0x${r.first.toString(16)}, .last = 0x${r.last.toString(16)}, .offset = ${offset} }, // ${r.name} (${count})`)
  offset += count
}
lines.push(`};`)
lines.push("")

// Lookup function
lines.push("/// O(1) per range lookup — returns atlas index or null if codepoint not covered.")
lines.push("pub fn lookup(codepoint: u32) ?u32 {")
lines.push("    inline for (ranges) |r| {")
lines.push("        if (codepoint >= r.first and codepoint <= r.last) {")
lines.push("            return r.offset + (codepoint - r.first);")
lines.push("        }")
lines.push("    }")
lines.push("    return null;")
lines.push("}")
lines.push("")

// Backward compat aliases for existing code that uses first_cp/last_cp
lines.push("// Backward compatibility — ASCII range")
lines.push(`pub const first_cp: u32 = 0x${RANGES[0].first.toString(16)};`)
lines.push(`pub const last_cp: u32 = 0x${RANGES[0].last.toString(16)};`)
lines.push("")

// Emit flat atlas data
const totalBytes = totalGlyphs * cellWidth * cellHeight
lines.push(`/// Flat atlas: ${totalGlyphs} glyphs x ${cellWidth}x${cellHeight}px = ${totalBytes} bytes (${(totalBytes / 1024).toFixed(1)} KB).`)
lines.push(`/// Index: lookup(codepoint) * ${cellWidth * cellHeight} + row * ${cellWidth} + col`)
lines.push(`pub const data = [_]u8{`)

for (const g of allGlyphs) {
  const ch = g.cp < 128
    ? (g.cp === 92 ? "\\\\" : g.cp === 39 ? "\\'" : String.fromCodePoint(g.cp))
    : String.fromCodePoint(g.cp)
  lines.push(`    // U+${g.cp.toString(16).toUpperCase().padStart(4, "0")} '${ch}'`)

  for (let row = 0; row < cellHeight; row++) {
    const rowData: string[] = []
    for (let col = 0; col < cellWidth; col++) {
      const val = g.alphas[row * cellWidth + col]
      rowData.push(val.toString().padStart(3))
    }
    lines.push(`    ${rowData.join(",")},`)
  }
}

lines.push("};")

const outPath = resolve(import.meta.dir, "../zig/src/font_atlas.zig")
writeFileSync(outPath, lines.join("\n") + "\n")
console.log(`\nWrote ${outPath}`)
console.log(`Atlas size: ${totalBytes} bytes (${(totalBytes / 1024).toFixed(1)} KB)`)
